# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minimal p5.js site
description: > # this means to ignore newlines until "baseurl:"
  This would probably be the kind of thing I'd use to get students started with
  p5 in a browser
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: davclark
github_username: davclark

# Build settings
markdown: kramdown
